name: Enable auto-delete branch on merge
description: Automatically delete head branches after PRs are merged

condition:
  not:
    - repo_setting:
        setting: delete_branch_on_merge
        value: true

actions:
  - type: update_repo_settings
    settings:
      delete_branch_on_merge: true
