name: Add Renovate validation workflow
description: Create a GitHub Actions workflow to validate Renovate configuration

condition:
  - and:
    - not:
        file_exists:
          path: .github/workflows/renovate.yml
    - or:
      - file_exists:
          path: renovate.json
      - file_exists:
          path: renovate.json5
      - file_exists:
          path: .github/renovate.json
      - file_exists:
          path: .github/renovate.json5

actions:
  - type: create_file
    path: .github/workflows/renovate.yml
    message: "Add Renovate validation workflow"
    content: |
      name: Renovate

      on:
        push:
          branches: [main]
          paths:
            - renovate.json5
            - renovate.json
            - .github/renovate.json5
            - .github/renovate.json
            - .github/workflows/renovate.yml
        pull_request:
          branches: ["main"]
          paths:
            - renovate.json5
            - renovate.json
            - .github/renovate.json5
            - .github/renovate.json
            - .github/workflows/renovate.yml

      permissions:
        contents: read

      jobs:
        validate:
          name: Validate
          runs-on: ubuntu-latest
          steps:
            - name: Checkout
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
              with:
                persist-credentials: false

            - name: Cache npm packages
              uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
              with:
                path: ~/.npm
                key: ${{ runner.os }}-npx-renovate

            - name: Validate Renovate configuration
              run: npx --yes --package renovate -- renovate-config-validator
