name: Renovate

on:
  push:
    branches: [main]
    paths: 
      - renovate.json5
      - renovate.json
      - .github/renovate.json5
      - .github/renovate.json
      - .github/workflows/renovate.yml
  pull_request:
    branches: ["main"]
    paths: 
      - renovate.json5
      - renovate.json
      - .github/renovate.json5
      - .github/renovate.json
      - .github/workflows/renovate.yml

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache npm packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npx-renovate

      - name: Validate Renovate configuration
        run: npx --yes --package renovate -- renovate-config-validator
