name: Self-hosted

on:
  push:
    branches: [main]
    paths: [renovate.json5]
  pull_request:
    branches: ["main"]
    paths: [renovate.json5]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sanity:
    name: Sanity check
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - run: cargo version

      - run: dotnet version
